# Generated by Django 2.0.5 on 2018-08-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180731_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='user',
            new_name='starter',
        ),
    ]
